fixtures:
  repositories:
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
    datacat: git://github.com/richardc/puppet-datacat.git
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    uchiwa: "#{source_dir}"
